## Risk_Prediction

In [1]:

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix
import joblib

import warnings
warnings.filterwarnings("ignore")

C:\Users\prasad ayithireddy\anaconda\Lib\site-packages\pandas\core\arrays\masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

In [5]:
df = pd.read_csv("preprocessed_dengue_data.csv")

In [6]:
df.head()

,Age,Gender,Temperature,Humidity,Rainfall,Platelet_Count,Outcome,Month,Year,Age_group,...,Symptom_fatigue,Symptom_Fever,Symptom_headache,Symptom_joint pain,Symptom_nausea,Symptom_bleeding,Symptom_retro-orbital pain,Symptom_chills,Symptom_rash,Outcome_encoded
0,48,0,25.7,82.8,45.0,110619,Recovered,6,2022,2,...,0,1,0,1,0,0,0,0,0,3
1,19,1,29.8,63.6,0.0,62974,Hospitalized,4,2022,1,...,0,1,0,0,0,0,1,0,0,2
2,33,1,23.8,92.9,10.0,78755,Hospitalized,7,2023,1,...,0,1,0,0,0,0,1,0,0,2
3,49,0,26.0,79.1,1.0,20787,Critical,8,2022,2,...,0,1,0,0,0,1,0,0,0,0
4,44,0,25.0,82.9,60.0,134421,Recovered,7,2024,2,...,0,1,0,0,0,0,0,0,0,3

In [7]:
df['High_Risk'] = df['Outcome'].apply(lambda x: 1 if x in ['Critical', 'Dead'] else 0)

In [8]:
df.head()

,Age,Gender,Temperature,Humidity,Rainfall,Platelet_Count,Outcome,Month,Year,Age_group,...,Symptom_Fever,Symptom_headache,Symptom_joint pain,Symptom_nausea,Symptom_bleeding,Symptom_retro-orbital pain,Symptom_chills,Symptom_rash,Outcome_encoded,High_Risk
0,48,0,25.7,82.8,45.0,110619,Recovered,6,2022,2,...,1,0,1,0,0,0,0,0,3,0
1,19,1,29.8,63.6,0.0,62974,Hospitalized,4,2022,1,...,1,0,0,0,0,1,0,0,2,0
2,33,1,23.8,92.9,10.0,78755,Hospitalized,7,2023,1,...,1,0,0,0,0,1,0,0,2,0
3,49,0,26.0,79.1,1.0,20787,Critical,8,2022,2,...,1,0,0,0,1,0,0,0,0,1
4,44,0,25.0,82.9,60.0,134421,Recovered,7,2024,2,...,1,0,0,0,0,0,0,0,3,0

In [9]:
df.columns

Index(['Age', 'Gender', 'Temperature', 'Humidity', 'Rainfall',
       'Platelet_Count', 'Outcome', 'Month', 'Year', 'Age_group',
       'Ward_Banjara Hills', 'Ward_Begumpet', 'Ward_Charminar',
       'Ward_Gachibowli', 'Ward_Jubilee Hills', 'Ward_Kukatpally',
       'Ward_LB Nagar', 'Ward_Malakpet', 'Ward_Mehdipatnam',
       'Ward_Musheerabad', 'Ward_Quthbullapur', 'Ward_Secunderabad',
       'Ward_Serilingampally', 'Ward_Uppal', 'Symptom_muscle pain',
       'Symptom_fatigue', 'Symptom_Fever', 'Symptom_headache',
       'Symptom_joint pain', 'Symptom_nausea', 'Symptom_bleeding',
       'Symptom_retro-orbital pain', 'Symptom_chills', 'Symptom_rash',
       'Outcome_encoded', 'High_Risk'],
      dtype='object')

In [10]:
X = df.drop(columns=["Outcome_encoded","Outcome","High_Risk"])

In [11]:
y = df["High_Risk"]