In [1]:

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix
import joblib

import warnings
warnings.filterwarnings("ignore")

C:\Users\prasad ayithireddy\anaconda\Lib\site-packages\pandas\core\arrays\masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

In [2]:
df = pd.read_csv("preprocessed_dengue_data.csv")
df1 = pd.read_csv("cleaned_dengue_data.csv")

In [3]:
df1.head()

,Patient_ID,Age,Gender,Ward,Date_of_diagnosis,Temperature,Humidity,Rainfall,Symptoms,Platelet_Count,Diagnosis,Outcome,Month,Year,Age_group
0,P00002,48,F,Mehdipatnam,2022-06-21,25.7,82.8,45.0,"Fever, joint pain",110619,Dengue+,Recovered,6,2022,Adult
1,P00003,19,M,Serilingampally,2022-04-01,29.8,63.6,0.0,"Fever, retro-orbital pain",62974,Dengue+,Hospitalized,4,2022,Young Adult
2,P00006,33,M,Mehdipatnam,2023-07-26,23.8,92.9,10.0,"Fever, retro-orbital pain",78755,Dengue+,Hospitalized,7,2023,Young Adult
3,P00010,49,F,Kukatpally,2022-08-20,26.0,79.1,1.0,"Fever, bleeding",20787,Dengue+,Critical,8,2022,Adult
4,P00011,44,F,Musheerabad,2024-07-14,25.0,82.9,60.0,"Fever, muscle pain",134421,Dengue+,Recovered,7,2024,Adult

In [4]:
# For example, create ward-wise demand based on the count of patients per ward
ward_counts = df1['Ward'].value_counts()
ward_demand = {}

for ward in ward_counts.index:
    count = ward_counts[ward]
    if count >= 400:
        ward_demand[ward] = 2  # High Demand
    elif count >= 200:
        ward_demand[ward] = 1  # Medium Demand
    else:
        ward_demand[ward] = 0  # Low Demand

df['Demand_encoded'] = df1['Ward'].map(ward_demand)

In [5]:
df1

,Patient_ID,Age,Gender,Ward,Date_of_diagnosis,Temperature,Humidity,Rainfall,Symptoms,Platelet_Count,Diagnosis,Outcome,Month,Year,Age_group
0,P00002,48,F,Mehdipatnam,2022-06-21,25.7,82.8,45.0,"Fever, joint pain",110619,Dengue+,Recovered,6,2022,Adult
1,P00003,19,M,Serilingampally,2022-04-01,29.8,63.6,0.0,"Fever, retro-orbital pain",62974,Dengue+,Hospitalized,4,2022,Young Adult
2,P00006,33,M,Mehdipatnam,2023-07-26,23.8,92.9,10.0,"Fever, retro-orbital pain",78755,Dengue+,Hospitalized,7,2023,Young Adult
3,P00010,49,F,Kukatpally,2022-08-20,26.0,79.1,1.0,"Fever, bleeding",20787,Dengue+,Critical,8,2022,Adult
4,P00011,44,F,Musheerabad,2024-07-14,25.0,82.9,60.0,"Fever, muscle pain",134421,Dengue+,Recovered,7,2024,Adult
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7966,P13524,20,M,Serilingampally,2022-08-07,24.1,92.5,3.0,"Fever, joint pain",136281,Dengue+,Recovered,8,2022,Young Adult
7967,P13525,34,M,Banjara Hills,2024-08-22,26.1,80.6,0.2,"Fever, muscle pain",127239,Dengue+,Recovered,8,2024,Young Adult
7968,P13526,27,M,Kukatpally,2023-05-05,27.4,71.4,2.6,"Fever, retro-orbital pain",24424,Dengue+,Critical,5,2023,Young Adult
7969,P13528,33,M,LB Nagar,2024-12-23,23.2,70.2,0.0,"Fever, headache, joint pain",33809,Dengue+,Critical,12,2024,Young Adult
7970,P13529,12,F,Kukatpally,2022-07-19,25.5,85.1,0.0,Fever,105785,Dengue+,Recovered,7,2022,Child

In [6]:
df.shape

(7971, 36)

In [7]:
df1.shape

(7971, 15)

In [9]:
df.head()

,Age,Gender,Temperature,Humidity,Rainfall,Platelet_Count,Outcome,Month,Year,Age_group,...,Symptom_Fever,Symptom_headache,Symptom_joint pain,Symptom_nausea,Symptom_bleeding,Symptom_retro-orbital pain,Symptom_chills,Symptom_rash,Outcome_encoded,Demand_encoded
0,48,0,25.7,82.8,45.0,110619,Recovered,6,2022,2,...,1,0,1,0,0,0,0,0,3,2
1,19,1,29.8,63.6,0.0,62974,Hospitalized,4,2022,1,...,1,0,0,0,0,1,0,0,2,2
2,33,1,23.8,92.9,10.0,78755,Hospitalized,7,2023,1,...,1,0,0,0,0,1,0,0,2,2
3,49,0,26.0,79.1,1.0,20787,Critical,8,2022,2,...,1,0,0,0,1,0,0,0,0,2
4,44,0,25.0,82.9,60.0,134421,Recovered,7,2024,2,...,1,0,0,0,0,0,0,0,3,2